name: updaterepovar
description: Updates a repo variable
inputs:
  variable:
    description: The variable name of the repository variable.
    type: string
  newvalue:
    description: The new value of the repository variable.
    type: string
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
