name: Test Action
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: pretoriustheuns/updaterepovar@03a574e5d4351a98134f91dba72070104ad9c1f8
        with:
          variable: MASTER_BUILDNOTES_LAST_COMMITSHA
          newvalue: testingfromaction
