name: Test Action
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: pretoriustheuns/updaterepovar@5b25bb73f5836b9d9c12bcdc5ac30551f1022118
        with:
          variable: MASTER_BUILDNOTES_LAST_COMMITSHA
          newvalue: testingfromaction
