name: Test Action
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: pretoriustheuns/updaterepovar@410eb7a588387df74cc89bf946f50846ee02dc8a
        with:
          variable: MASTER_BUILDNOTES_LAST_COMMITSHA
          newvalue: testingfromaction
