name: Test Action
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: pretoriustheuns/updaterepovar@bec8c4aa833a6bfe4c64750c8d7369b785316be0
        with:
          variable: MASTER_BUILDNOTES_LAST_COMMITSHA
          newvalue: testingfromaction
