name: Test Action
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: pretoriustheuns/updaterepovar@06f2545ee6f2691aa62c5760e7ee5bbaece61d09
        with:
          variable: MASTER_BUILDNOTES_LAST_COMMITSHA
          newvalue: testingfromaction
